module.exports = [
  './gulp/tasks/del.js',
  './gulp/tasks/copy.js',
  './gulp/tasks/pug.js',
  './gulp/tasks/browserSync.js',
  './gulp/tasks/watcher.js',
  './gulp/tasks/sass.js',
  './gulp/tasks/script.js',
  './gulp/tasks/scriptLib.js',
  './gulp/tasks/script11.js',
  './gulp/tasks/libsCSS.js',
  './gulp/tasks/images.js',
  './gulp/tasks/jimpContent.js',
  './gulp/tasks/jimpDecor.js',
  './gulp/tasks/svgSprite.js',
];
